services:
  backend:
    build: ./backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_NAME: urlshortener
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - docker

  postgres:
    image: postgres:latest
    build: ./database
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - docker

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - docker

networks:
  docker:
    driver: bridge
